// Code generated by mockery. DO NOT EDIT.

package mockLog

import (
	mock "github.com/stretchr/testify/mock"
	zap "go.uber.org/zap"
)

// MockLoggerInterface is an autogenerated mock type for the LoggerInterface type
type MockLoggerInterface struct {
	mock.Mock
}

type MockLoggerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerInterface) EXPECT() *MockLoggerInterface_Expecter {
	return &MockLoggerInterface_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: msg, keyvals
func (_m *MockLoggerInterface) Debug(msg string, keyvals ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, keyvals...)
	_m.Called(_ca...)
}

// MockLoggerInterface_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLoggerInterface_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Debug(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Debug_Call {
	return &MockLoggerInterface_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Debug_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerInterface_Debug_Call) Return() *MockLoggerInterface_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Debug_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerInterface_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: msg, keyvals
func (_m *MockLoggerInterface) Error(msg string, keyvals ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, keyvals...)
	_m.Called(_ca...)
}

// MockLoggerInterface_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLoggerInterface_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Error(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Error_Call {
	return &MockLoggerInterface_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Error_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerInterface_Error_Call) Return() *MockLoggerInterface_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Error_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerInterface_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: msg, keyvals
func (_m *MockLoggerInterface) Info(msg string, keyvals ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, keyvals...)
	_m.Called(_ca...)
}

// MockLoggerInterface_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLoggerInterface_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Info(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Info_Call {
	return &MockLoggerInterface_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Info_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerInterface_Info_Call) Return() *MockLoggerInterface_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerInterface_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function with given fields:
func (_m *MockLoggerInterface) Logger() *zap.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *zap.Logger
	if rf, ok := ret.Get(0).(func() *zap.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zap.Logger)
		}
	}

	return r0
}

// MockLoggerInterface_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockLoggerInterface_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockLoggerInterface_Expecter) Logger() *MockLoggerInterface_Logger_Call {
	return &MockLoggerInterface_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockLoggerInterface_Logger_Call) Run(run func()) *MockLoggerInterface_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerInterface_Logger_Call) Return(_a0 *zap.Logger) *MockLoggerInterface_Logger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerInterface_Logger_Call) RunAndReturn(run func() *zap.Logger) *MockLoggerInterface_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SendError provides a mock function with given fields: errMessage, addlContext, errorType
func (_m *MockLoggerInterface) SendError(errMessage string, addlContext map[string]interface{}, errorType string) {
	_m.Called(errMessage, addlContext, errorType)
}

// MockLoggerInterface_SendError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendError'
type MockLoggerInterface_SendError_Call struct {
	*mock.Call
}

// SendError is a helper method to define mock.On call
//   - errMessage string
//   - addlContext map[string]interface{}
//   - errorType string
func (_e *MockLoggerInterface_Expecter) SendError(errMessage interface{}, addlContext interface{}, errorType interface{}) *MockLoggerInterface_SendError_Call {
	return &MockLoggerInterface_SendError_Call{Call: _e.mock.On("SendError", errMessage, addlContext, errorType)}
}

func (_c *MockLoggerInterface_SendError_Call) Run(run func(errMessage string, addlContext map[string]interface{}, errorType string)) *MockLoggerInterface_SendError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockLoggerInterface_SendError_Call) Return() *MockLoggerInterface_SendError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_SendError_Call) RunAndReturn(run func(string, map[string]interface{}, string)) *MockLoggerInterface_SendError_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: msg, keyvals
func (_m *MockLoggerInterface) Warn(msg string, keyvals ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, keyvals...)
	_m.Called(_ca...)
}

// MockLoggerInterface_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLoggerInterface_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Warn(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Warn_Call {
	return &MockLoggerInterface_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Warn_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerInterface_Warn_Call) Return() *MockLoggerInterface_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Warn_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerInterface_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoggerInterface creates a new instance of MockLoggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerInterface {
	mock := &MockLoggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
