// Code generated by mockery. DO NOT EDIT.

package mockDomain

import (
	context "context"

	domain "github.com/GalaDe/payments-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeletePlaidToken provides a mock function with given fields: ctx, userID
func (_m *MockRepository) DeletePlaidToken(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlaidToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeletePlaidToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlaidToken'
type MockRepository_DeletePlaidToken_Call struct {
	*mock.Call
}

// DeletePlaidToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) DeletePlaidToken(ctx interface{}, userID interface{}) *MockRepository_DeletePlaidToken_Call {
	return &MockRepository_DeletePlaidToken_Call{Call: _e.mock.On("DeletePlaidToken", ctx, userID)}
}

func (_c *MockRepository_DeletePlaidToken_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_DeletePlaidToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeletePlaidToken_Call) Return(_a0 error) *MockRepository_DeletePlaidToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeletePlaidToken_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeletePlaidToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPayments provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllPayments(ctx context.Context) ([]*domain.Payment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayments")
	}

	var r0 []*domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Payment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Payment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPayments'
type MockRepository_GetAllPayments_Call struct {
	*mock.Call
}

// GetAllPayments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllPayments(ctx interface{}) *MockRepository_GetAllPayments_Call {
	return &MockRepository_GetAllPayments_Call{Call: _e.mock.On("GetAllPayments", ctx)}
}

func (_c *MockRepository_GetAllPayments_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetAllPayments_Call) Return(_a0 []*domain.Payment, _a1 error) *MockRepository_GetAllPayments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllPayments_Call) RunAndReturn(run func(context.Context) ([]*domain.Payment, error)) *MockRepository_GetAllPayments_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentByID provides a mock function with given fields: ctx, paymentID
func (_m *MockRepository) GetPaymentByID(ctx context.Context, paymentID string) (*domain.Payment, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPaymentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentByID'
type MockRepository_GetPaymentByID_Call struct {
	*mock.Call
}

// GetPaymentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockRepository_Expecter) GetPaymentByID(ctx interface{}, paymentID interface{}) *MockRepository_GetPaymentByID_Call {
	return &MockRepository_GetPaymentByID_Call{Call: _e.mock.On("GetPaymentByID", ctx, paymentID)}
}

func (_c *MockRepository_GetPaymentByID_Call) Run(run func(ctx context.Context, paymentID string)) *MockRepository_GetPaymentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetPaymentByID_Call) Return(_a0 *domain.Payment, _a1 error) *MockRepository_GetPaymentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPaymentByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Payment, error)) *MockRepository_GetPaymentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlaidToken provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetPlaidToken(ctx context.Context, userID string) (*domain.PlaidToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaidToken")
	}

	var r0 *domain.PlaidToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PlaidToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PlaidToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PlaidToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPlaidToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaidToken'
type MockRepository_GetPlaidToken_Call struct {
	*mock.Call
}

// GetPlaidToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetPlaidToken(ctx interface{}, userID interface{}) *MockRepository_GetPlaidToken_Call {
	return &MockRepository_GetPlaidToken_Call{Call: _e.mock.On("GetPlaidToken", ctx, userID)}
}

func (_c *MockRepository_GetPlaidToken_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetPlaidToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetPlaidToken_Call) Return(_a0 *domain.PlaidToken, _a1 error) *MockRepository_GetPlaidToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPlaidToken_Call) RunAndReturn(run func(context.Context, string) (*domain.PlaidToken, error)) *MockRepository_GetPlaidToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetStripeCustomerByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetStripeCustomerByUserID(ctx context.Context, userID string) (*domain.StripeCustomer, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStripeCustomerByUserID")
	}

	var r0 *domain.StripeCustomer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.StripeCustomer, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.StripeCustomer); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StripeCustomer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetStripeCustomerByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStripeCustomerByUserID'
type MockRepository_GetStripeCustomerByUserID_Call struct {
	*mock.Call
}

// GetStripeCustomerByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetStripeCustomerByUserID(ctx interface{}, userID interface{}) *MockRepository_GetStripeCustomerByUserID_Call {
	return &MockRepository_GetStripeCustomerByUserID_Call{Call: _e.mock.On("GetStripeCustomerByUserID", ctx, userID)}
}

func (_c *MockRepository_GetStripeCustomerByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetStripeCustomerByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetStripeCustomerByUserID_Call) Return(_a0 *domain.StripeCustomer, _a1 error) *MockRepository_GetStripeCustomerByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetStripeCustomerByUserID_Call) RunAndReturn(run func(context.Context, string) (*domain.StripeCustomer, error)) *MockRepository_GetStripeCustomerByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPayment provides a mock function with given fields: ctx, payment
func (_m *MockRepository) InsertPayment(ctx context.Context, payment *domain.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for InsertPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPayment'
type MockRepository_InsertPayment_Call struct {
	*mock.Call
}

// InsertPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *domain.Payment
func (_e *MockRepository_Expecter) InsertPayment(ctx interface{}, payment interface{}) *MockRepository_InsertPayment_Call {
	return &MockRepository_InsertPayment_Call{Call: _e.mock.On("InsertPayment", ctx, payment)}
}

func (_c *MockRepository_InsertPayment_Call) Run(run func(ctx context.Context, payment *domain.Payment)) *MockRepository_InsertPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Payment))
	})
	return _c
}

func (_c *MockRepository_InsertPayment_Call) Return(_a0 error) *MockRepository_InsertPayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertPayment_Call) RunAndReturn(run func(context.Context, *domain.Payment) error) *MockRepository_InsertPayment_Call {
	_c.Call.Return(run)
	return _c
}

// InsertStripeCustomer provides a mock function with given fields: ctx, customer
func (_m *MockRepository) InsertStripeCustomer(ctx context.Context, customer *domain.StripeCustomer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for InsertStripeCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StripeCustomer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertStripeCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertStripeCustomer'
type MockRepository_InsertStripeCustomer_Call struct {
	*mock.Call
}

// InsertStripeCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *domain.StripeCustomer
func (_e *MockRepository_Expecter) InsertStripeCustomer(ctx interface{}, customer interface{}) *MockRepository_InsertStripeCustomer_Call {
	return &MockRepository_InsertStripeCustomer_Call{Call: _e.mock.On("InsertStripeCustomer", ctx, customer)}
}

func (_c *MockRepository_InsertStripeCustomer_Call) Run(run func(ctx context.Context, customer *domain.StripeCustomer)) *MockRepository_InsertStripeCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StripeCustomer))
	})
	return _c
}

func (_c *MockRepository_InsertStripeCustomer_Call) Return(_a0 error) *MockRepository_InsertStripeCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertStripeCustomer_Call) RunAndReturn(run func(context.Context, *domain.StripeCustomer) error) *MockRepository_InsertStripeCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// StorePlaidToken provides a mock function with given fields: ctx, token
func (_m *MockRepository) StorePlaidToken(ctx context.Context, token domain.PlaidToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for StorePlaidToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlaidToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_StorePlaidToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorePlaidToken'
type MockRepository_StorePlaidToken_Call struct {
	*mock.Call
}

// StorePlaidToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.PlaidToken
func (_e *MockRepository_Expecter) StorePlaidToken(ctx interface{}, token interface{}) *MockRepository_StorePlaidToken_Call {
	return &MockRepository_StorePlaidToken_Call{Call: _e.mock.On("StorePlaidToken", ctx, token)}
}

func (_c *MockRepository_StorePlaidToken_Call) Run(run func(ctx context.Context, token domain.PlaidToken)) *MockRepository_StorePlaidToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PlaidToken))
	})
	return _c
}

func (_c *MockRepository_StorePlaidToken_Call) Return(_a0 error) *MockRepository_StorePlaidToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_StorePlaidToken_Call) RunAndReturn(run func(context.Context, domain.PlaidToken) error) *MockRepository_StorePlaidToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, paymentID, status
func (_m *MockRepository) UpdatePaymentStatus(ctx context.Context, paymentID string, status string) error {
	ret := _m.Called(ctx, paymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, paymentID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type MockRepository_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
//   - status string
func (_e *MockRepository_Expecter) UpdatePaymentStatus(ctx interface{}, paymentID interface{}, status interface{}) *MockRepository_UpdatePaymentStatus_Call {
	return &MockRepository_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", ctx, paymentID, status)}
}

func (_c *MockRepository_UpdatePaymentStatus_Call) Run(run func(ctx context.Context, paymentID string, status string)) *MockRepository_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdatePaymentStatus_Call) Return(_a0 error) *MockRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePaymentStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
