// Code generated by mockery. DO NOT EDIT.

package mockDomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	orm "github.com/GalaDe/payments-service/internal/sqlc"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// WithQtx provides a mock function with given fields: ctx
func (_m *MockTransactor) WithQtx(ctx context.Context) orm.Querier {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithQtx")
	}

	var r0 orm.Querier
	if rf, ok := ret.Get(0).(func(context.Context) orm.Querier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Querier)
		}
	}

	return r0
}

// MockTransactor_WithQtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithQtx'
type MockTransactor_WithQtx_Call struct {
	*mock.Call
}

// WithQtx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactor_Expecter) WithQtx(ctx interface{}) *MockTransactor_WithQtx_Call {
	return &MockTransactor_WithQtx_Call{Call: _e.mock.On("WithQtx", ctx)}
}

func (_c *MockTransactor_WithQtx_Call) Run(run func(ctx context.Context)) *MockTransactor_WithQtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactor_WithQtx_Call) Return(_a0 orm.Querier) *MockTransactor_WithQtx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_WithQtx_Call) RunAndReturn(run func(context.Context) orm.Querier) *MockTransactor_WithQtx_Call {
	_c.Call.Return(run)
	return _c
}

// WithinTransaction provides a mock function with given fields: _a0, _a1
func (_m *MockTransactor) WithinTransaction(_a0 context.Context, _a1 func(context.Context) error) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTransactor_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 func(context.Context) error
func (_e *MockTransactor_Expecter) WithinTransaction(_a0 interface{}, _a1 interface{}) *MockTransactor_WithinTransaction_Call {
	return &MockTransactor_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", _a0, _a1)}
}

func (_c *MockTransactor_WithinTransaction_Call) Run(run func(_a0 context.Context, _a1 func(context.Context) error)) *MockTransactor_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) Return(_a0 error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_WithinTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockTransactor_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
