// Code generated by mockery. DO NOT EDIT.

package mockPostgres

import mock "github.com/stretchr/testify/mock"

// MockPostgresInterface is an autogenerated mock type for the PostgresInterface type
type MockPostgresInterface struct {
	mock.Mock
}

type MockPostgresInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresInterface) EXPECT() *MockPostgresInterface_Expecter {
	return &MockPostgresInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockPostgresInterface) Close() {
	_m.Called()
}

// MockPostgresInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPostgresInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPostgresInterface_Expecter) Close() *MockPostgresInterface_Close_Call {
	return &MockPostgresInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPostgresInterface_Close_Call) Run(run func()) *MockPostgresInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresInterface_Close_Call) Return() *MockPostgresInterface_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPostgresInterface_Close_Call) RunAndReturn(run func()) *MockPostgresInterface_Close_Call {
	_c.Run(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockPostgresInterface) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostgresInterface_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPostgresInterface_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockPostgresInterface_Expecter) Ping() *MockPostgresInterface_Ping_Call {
	return &MockPostgresInterface_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockPostgresInterface_Ping_Call) Run(run func()) *MockPostgresInterface_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresInterface_Ping_Call) Return(_a0 error) *MockPostgresInterface_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresInterface_Ping_Call) RunAndReturn(run func() error) *MockPostgresInterface_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostgresInterface creates a new instance of MockPostgresInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresInterface {
	mock := &MockPostgresInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
