// Code generated by mockery. DO NOT EDIT.

package mockPlaid

import (
	context "context"

	plaid "github.com/GalaDe/payments-service/internal/services/plaid"
	mock "github.com/stretchr/testify/mock"

	v12plaid "github.com/plaid/plaid-go/v12/plaid"
)

// MockPlaidService is an autogenerated mock type for the PlaidService type
type MockPlaidService struct {
	mock.Mock
}

type MockPlaidService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaidService) EXPECT() *MockPlaidService_Expecter {
	return &MockPlaidService_Expecter{mock: &_m.Mock}
}

// CreateLinkToken provides a mock function with given fields: ctx, userID
func (_m *MockPlaidService) CreateLinkToken(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinkToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_CreateLinkToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinkToken'
type MockPlaidService_CreateLinkToken_Call struct {
	*mock.Call
}

// CreateLinkToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPlaidService_Expecter) CreateLinkToken(ctx interface{}, userID interface{}) *MockPlaidService_CreateLinkToken_Call {
	return &MockPlaidService_CreateLinkToken_Call{Call: _e.mock.On("CreateLinkToken", ctx, userID)}
}

func (_c *MockPlaidService_CreateLinkToken_Call) Run(run func(ctx context.Context, userID string)) *MockPlaidService_CreateLinkToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlaidService_CreateLinkToken_Call) Return(_a0 string, _a1 error) *MockPlaidService_CreateLinkToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_CreateLinkToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockPlaidService_CreateLinkToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePlaidBankAccount provides a mock function with given fields: ctx
func (_m *MockPlaidService) CreatePlaidBankAccount(ctx context.Context) (*plaid.CreatePlaidBankAccountResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaidBankAccount")
	}

	var r0 *plaid.CreatePlaidBankAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*plaid.CreatePlaidBankAccountResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *plaid.CreatePlaidBankAccountResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plaid.CreatePlaidBankAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_CreatePlaidBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlaidBankAccount'
type MockPlaidService_CreatePlaidBankAccount_Call struct {
	*mock.Call
}

// CreatePlaidBankAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPlaidService_Expecter) CreatePlaidBankAccount(ctx interface{}) *MockPlaidService_CreatePlaidBankAccount_Call {
	return &MockPlaidService_CreatePlaidBankAccount_Call{Call: _e.mock.On("CreatePlaidBankAccount", ctx)}
}

func (_c *MockPlaidService_CreatePlaidBankAccount_Call) Run(run func(ctx context.Context)) *MockPlaidService_CreatePlaidBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPlaidService_CreatePlaidBankAccount_Call) Return(_a0 *plaid.CreatePlaidBankAccountResponse, _a1 error) *MockPlaidService_CreatePlaidBankAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_CreatePlaidBankAccount_Call) RunAndReturn(run func(context.Context) (*plaid.CreatePlaidBankAccountResponse, error)) *MockPlaidService_CreatePlaidBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProcessorToken provides a mock function with given fields: ctx, accessToken, accountID
func (_m *MockPlaidService) CreateProcessorToken(ctx context.Context, accessToken string, accountID string) (string, error) {
	ret := _m.Called(ctx, accessToken, accountID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcessorToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, accessToken, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, accessToken, accountID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_CreateProcessorToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcessorToken'
type MockPlaidService_CreateProcessorToken_Call struct {
	*mock.Call
}

// CreateProcessorToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - accountID string
func (_e *MockPlaidService_Expecter) CreateProcessorToken(ctx interface{}, accessToken interface{}, accountID interface{}) *MockPlaidService_CreateProcessorToken_Call {
	return &MockPlaidService_CreateProcessorToken_Call{Call: _e.mock.On("CreateProcessorToken", ctx, accessToken, accountID)}
}

func (_c *MockPlaidService_CreateProcessorToken_Call) Run(run func(ctx context.Context, accessToken string, accountID string)) *MockPlaidService_CreateProcessorToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPlaidService_CreateProcessorToken_Call) Return(_a0 string, _a1 error) *MockPlaidService_CreateProcessorToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_CreateProcessorToken_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockPlaidService_CreateProcessorToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStripeToken provides a mock function with given fields: ctx, accessToken, accountID
func (_m *MockPlaidService) CreateStripeToken(ctx context.Context, accessToken string, accountID string) (*string, error) {
	ret := _m.Called(ctx, accessToken, accountID)

	if len(ret) == 0 {
		panic("no return value specified for CreateStripeToken")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*string, error)); ok {
		return rf(ctx, accessToken, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *string); ok {
		r0 = rf(ctx, accessToken, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_CreateStripeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStripeToken'
type MockPlaidService_CreateStripeToken_Call struct {
	*mock.Call
}

// CreateStripeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - accountID string
func (_e *MockPlaidService_Expecter) CreateStripeToken(ctx interface{}, accessToken interface{}, accountID interface{}) *MockPlaidService_CreateStripeToken_Call {
	return &MockPlaidService_CreateStripeToken_Call{Call: _e.mock.On("CreateStripeToken", ctx, accessToken, accountID)}
}

func (_c *MockPlaidService_CreateStripeToken_Call) Run(run func(ctx context.Context, accessToken string, accountID string)) *MockPlaidService_CreateStripeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPlaidService_CreateStripeToken_Call) Return(_a0 *string, _a1 error) *MockPlaidService_CreateStripeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_CreateStripeToken_Call) RunAndReturn(run func(context.Context, string, string) (*string, error)) *MockPlaidService_CreateStripeToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlaidBankAccount provides a mock function with given fields: ctx, accessToken
func (_m *MockPlaidService) DeletePlaidBankAccount(ctx context.Context, accessToken string) (*string, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlaidBankAccount")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_DeletePlaidBankAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlaidBankAccount'
type MockPlaidService_DeletePlaidBankAccount_Call struct {
	*mock.Call
}

// DeletePlaidBankAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockPlaidService_Expecter) DeletePlaidBankAccount(ctx interface{}, accessToken interface{}) *MockPlaidService_DeletePlaidBankAccount_Call {
	return &MockPlaidService_DeletePlaidBankAccount_Call{Call: _e.mock.On("DeletePlaidBankAccount", ctx, accessToken)}
}

func (_c *MockPlaidService_DeletePlaidBankAccount_Call) Run(run func(ctx context.Context, accessToken string)) *MockPlaidService_DeletePlaidBankAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlaidService_DeletePlaidBankAccount_Call) Return(_a0 *string, _a1 error) *MockPlaidService_DeletePlaidBankAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_DeletePlaidBankAccount_Call) RunAndReturn(run func(context.Context, string) (*string, error)) *MockPlaidService_DeletePlaidBankAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangePublicToken provides a mock function with given fields: ctx, publicToken
func (_m *MockPlaidService) ExchangePublicToken(ctx context.Context, publicToken string) (*plaid.ExchangeTokenResponse, error) {
	ret := _m.Called(ctx, publicToken)

	if len(ret) == 0 {
		panic("no return value specified for ExchangePublicToken")
	}

	var r0 *plaid.ExchangeTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*plaid.ExchangeTokenResponse, error)); ok {
		return rf(ctx, publicToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *plaid.ExchangeTokenResponse); ok {
		r0 = rf(ctx, publicToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plaid.ExchangeTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_ExchangePublicToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangePublicToken'
type MockPlaidService_ExchangePublicToken_Call struct {
	*mock.Call
}

// ExchangePublicToken is a helper method to define mock.On call
//   - ctx context.Context
//   - publicToken string
func (_e *MockPlaidService_Expecter) ExchangePublicToken(ctx interface{}, publicToken interface{}) *MockPlaidService_ExchangePublicToken_Call {
	return &MockPlaidService_ExchangePublicToken_Call{Call: _e.mock.On("ExchangePublicToken", ctx, publicToken)}
}

func (_c *MockPlaidService_ExchangePublicToken_Call) Run(run func(ctx context.Context, publicToken string)) *MockPlaidService_ExchangePublicToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlaidService_ExchangePublicToken_Call) Return(_a0 *plaid.ExchangeTokenResponse, _a1 error) *MockPlaidService_ExchangePublicToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_ExchangePublicToken_Call) RunAndReturn(run func(context.Context, string) (*plaid.ExchangeTokenResponse, error)) *MockPlaidService_ExchangePublicToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, accessToken, accountID
func (_m *MockPlaidService) GetAccount(ctx context.Context, accessToken string, accountID string) (*plaid.Account, error) {
	ret := _m.Called(ctx, accessToken, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *plaid.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*plaid.Account, error)); ok {
		return rf(ctx, accessToken, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *plaid.Account); ok {
		r0 = rf(ctx, accessToken, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plaid.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockPlaidService_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - accountID string
func (_e *MockPlaidService_Expecter) GetAccount(ctx interface{}, accessToken interface{}, accountID interface{}) *MockPlaidService_GetAccount_Call {
	return &MockPlaidService_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accessToken, accountID)}
}

func (_c *MockPlaidService_GetAccount_Call) Run(run func(ctx context.Context, accessToken string, accountID string)) *MockPlaidService_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPlaidService_GetAccount_Call) Return(_a0 *plaid.Account, _a1 error) *MockPlaidService_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_GetAccount_Call) RunAndReturn(run func(context.Context, string, string) (*plaid.Account, error)) *MockPlaidService_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountWithBalance provides a mock function with given fields: ctx, accessToken, accountID
func (_m *MockPlaidService) GetAccountWithBalance(ctx context.Context, accessToken string, accountID string) (*plaid.AccountWithBalance, error) {
	ret := _m.Called(ctx, accessToken, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountWithBalance")
	}

	var r0 *plaid.AccountWithBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*plaid.AccountWithBalance, error)); ok {
		return rf(ctx, accessToken, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *plaid.AccountWithBalance); ok {
		r0 = rf(ctx, accessToken, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plaid.AccountWithBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_GetAccountWithBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountWithBalance'
type MockPlaidService_GetAccountWithBalance_Call struct {
	*mock.Call
}

// GetAccountWithBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - accountID string
func (_e *MockPlaidService_Expecter) GetAccountWithBalance(ctx interface{}, accessToken interface{}, accountID interface{}) *MockPlaidService_GetAccountWithBalance_Call {
	return &MockPlaidService_GetAccountWithBalance_Call{Call: _e.mock.On("GetAccountWithBalance", ctx, accessToken, accountID)}
}

func (_c *MockPlaidService_GetAccountWithBalance_Call) Run(run func(ctx context.Context, accessToken string, accountID string)) *MockPlaidService_GetAccountWithBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPlaidService_GetAccountWithBalance_Call) Return(_a0 *plaid.AccountWithBalance, _a1 error) *MockPlaidService_GetAccountWithBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_GetAccountWithBalance_Call) RunAndReturn(run func(context.Context, string, string) (*plaid.AccountWithBalance, error)) *MockPlaidService_GetAccountWithBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebhookVerification provides a mock function with given fields: ctx, _a1
func (_m *MockPlaidService) GetWebhookVerification(ctx context.Context, _a1 *v12plaid.WebhookVerificationKeyGetRequest) (*v12plaid.JWKPublicKey, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookVerification")
	}

	var r0 *v12plaid.JWKPublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v12plaid.WebhookVerificationKeyGetRequest) (*v12plaid.JWKPublicKey, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v12plaid.WebhookVerificationKeyGetRequest) *v12plaid.JWKPublicKey); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12plaid.JWKPublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v12plaid.WebhookVerificationKeyGetRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_GetWebhookVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebhookVerification'
type MockPlaidService_GetWebhookVerification_Call struct {
	*mock.Call
}

// GetWebhookVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v12plaid.WebhookVerificationKeyGetRequest
func (_e *MockPlaidService_Expecter) GetWebhookVerification(ctx interface{}, _a1 interface{}) *MockPlaidService_GetWebhookVerification_Call {
	return &MockPlaidService_GetWebhookVerification_Call{Call: _e.mock.On("GetWebhookVerification", ctx, _a1)}
}

func (_c *MockPlaidService_GetWebhookVerification_Call) Run(run func(ctx context.Context, _a1 *v12plaid.WebhookVerificationKeyGetRequest)) *MockPlaidService_GetWebhookVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v12plaid.WebhookVerificationKeyGetRequest))
	})
	return _c
}

func (_c *MockPlaidService_GetWebhookVerification_Call) Return(_a0 *v12plaid.JWKPublicKey, _a1 error) *MockPlaidService_GetWebhookVerification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_GetWebhookVerification_Call) RunAndReturn(run func(context.Context, *v12plaid.WebhookVerificationKeyGetRequest) (*v12plaid.JWKPublicKey, error)) *MockPlaidService_GetWebhookVerification_Call {
	_c.Call.Return(run)
	return _c
}

// IsBalanceCheckSupported provides a mock function with given fields: ctx, accessToken, accountID
func (_m *MockPlaidService) IsBalanceCheckSupported(ctx context.Context, accessToken string, accountID string) (bool, error) {
	ret := _m.Called(ctx, accessToken, accountID)

	if len(ret) == 0 {
		panic("no return value specified for IsBalanceCheckSupported")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, accessToken, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, accessToken, accountID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_IsBalanceCheckSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBalanceCheckSupported'
type MockPlaidService_IsBalanceCheckSupported_Call struct {
	*mock.Call
}

// IsBalanceCheckSupported is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - accountID string
func (_e *MockPlaidService_Expecter) IsBalanceCheckSupported(ctx interface{}, accessToken interface{}, accountID interface{}) *MockPlaidService_IsBalanceCheckSupported_Call {
	return &MockPlaidService_IsBalanceCheckSupported_Call{Call: _e.mock.On("IsBalanceCheckSupported", ctx, accessToken, accountID)}
}

func (_c *MockPlaidService_IsBalanceCheckSupported_Call) Run(run func(ctx context.Context, accessToken string, accountID string)) *MockPlaidService_IsBalanceCheckSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPlaidService_IsBalanceCheckSupported_Call) Return(_a0 bool, _a1 error) *MockPlaidService_IsBalanceCheckSupported_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_IsBalanceCheckSupported_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockPlaidService_IsBalanceCheckSupported_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyWebhook provides a mock function with given fields: webhookBody, headers
func (_m *MockPlaidService) VerifyWebhook(webhookBody string, headers map[string]string) (bool, error) {
	ret := _m.Called(webhookBody, headers)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhook")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) (bool, error)); ok {
		return rf(webhookBody, headers)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string) bool); ok {
		r0 = rf(webhookBody, headers)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(webhookBody, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaidService_VerifyWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWebhook'
type MockPlaidService_VerifyWebhook_Call struct {
	*mock.Call
}

// VerifyWebhook is a helper method to define mock.On call
//   - webhookBody string
//   - headers map[string]string
func (_e *MockPlaidService_Expecter) VerifyWebhook(webhookBody interface{}, headers interface{}) *MockPlaidService_VerifyWebhook_Call {
	return &MockPlaidService_VerifyWebhook_Call{Call: _e.mock.On("VerifyWebhook", webhookBody, headers)}
}

func (_c *MockPlaidService_VerifyWebhook_Call) Run(run func(webhookBody string, headers map[string]string)) *MockPlaidService_VerifyWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockPlaidService_VerifyWebhook_Call) Return(_a0 bool, _a1 error) *MockPlaidService_VerifyWebhook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaidService_VerifyWebhook_Call) RunAndReturn(run func(string, map[string]string) (bool, error)) *MockPlaidService_VerifyWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlaidService creates a new instance of MockPlaidService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaidService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaidService {
	mock := &MockPlaidService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
