// Code generated by mockery. DO NOT EDIT.

package mockStripe

import (
	context "context"

	domain "github.com/GalaDe/payments-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	stripe "github.com/GalaDe/payments-service/internal/services/stripe"

	v75 "github.com/stripe/stripe-go/v75"
)

// MockStripeService is an autogenerated mock type for the StripeService type
type MockStripeService struct {
	mock.Mock
}

type MockStripeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStripeService) EXPECT() *MockStripeService_Expecter {
	return &MockStripeService_Expecter{mock: &_m.Mock}
}

// CreateACHCharge provides a mock function with given fields: ctx, input
func (_m *MockStripeService) CreateACHCharge(ctx context.Context, input *stripe.CreateACHChargeInput) (*stripe.ACHCharge, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateACHCharge")
	}

	var r0 *stripe.ACHCharge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *stripe.CreateACHChargeInput) (*stripe.ACHCharge, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *stripe.CreateACHChargeInput) *stripe.ACHCharge); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.ACHCharge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *stripe.CreateACHChargeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_CreateACHCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateACHCharge'
type MockStripeService_CreateACHCharge_Call struct {
	*mock.Call
}

// CreateACHCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - input *stripe.CreateACHChargeInput
func (_e *MockStripeService_Expecter) CreateACHCharge(ctx interface{}, input interface{}) *MockStripeService_CreateACHCharge_Call {
	return &MockStripeService_CreateACHCharge_Call{Call: _e.mock.On("CreateACHCharge", ctx, input)}
}

func (_c *MockStripeService_CreateACHCharge_Call) Run(run func(ctx context.Context, input *stripe.CreateACHChargeInput)) *MockStripeService_CreateACHCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*stripe.CreateACHChargeInput))
	})
	return _c
}

func (_c *MockStripeService_CreateACHCharge_Call) Return(_a0 *stripe.ACHCharge, _a1 error) *MockStripeService_CreateACHCharge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_CreateACHCharge_Call) RunAndReturn(run func(context.Context, *stripe.CreateACHChargeInput) (*stripe.ACHCharge, error)) *MockStripeService_CreateACHCharge_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentMethodFromBankToken provides a mock function with given fields: ctx, customerID, processorToken
func (_m *MockStripeService) CreatePaymentMethodFromBankToken(ctx context.Context, customerID string, processorToken string) (*domain.PaymentMethod, error) {
	ret := _m.Called(ctx, customerID, processorToken)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentMethodFromBankToken")
	}

	var r0 *domain.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PaymentMethod, error)); ok {
		return rf(ctx, customerID, processorToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.PaymentMethod); ok {
		r0 = rf(ctx, customerID, processorToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, customerID, processorToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_CreatePaymentMethodFromBankToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentMethodFromBankToken'
type MockStripeService_CreatePaymentMethodFromBankToken_Call struct {
	*mock.Call
}

// CreatePaymentMethodFromBankToken is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - processorToken string
func (_e *MockStripeService_Expecter) CreatePaymentMethodFromBankToken(ctx interface{}, customerID interface{}, processorToken interface{}) *MockStripeService_CreatePaymentMethodFromBankToken_Call {
	return &MockStripeService_CreatePaymentMethodFromBankToken_Call{Call: _e.mock.On("CreatePaymentMethodFromBankToken", ctx, customerID, processorToken)}
}

func (_c *MockStripeService_CreatePaymentMethodFromBankToken_Call) Run(run func(ctx context.Context, customerID string, processorToken string)) *MockStripeService_CreatePaymentMethodFromBankToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStripeService_CreatePaymentMethodFromBankToken_Call) Return(_a0 *domain.PaymentMethod, _a1 error) *MockStripeService_CreatePaymentMethodFromBankToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_CreatePaymentMethodFromBankToken_Call) RunAndReturn(run func(context.Context, string, string) (*domain.PaymentMethod, error)) *MockStripeService_CreatePaymentMethodFromBankToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStripeCustomer provides a mock function with given fields: input
func (_m *MockStripeService) CreateStripeCustomer(input *stripe.CreateStripeCustomerInput) (*domain.StripeCustomer, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateStripeCustomer")
	}

	var r0 *domain.StripeCustomer
	var r1 error
	if rf, ok := ret.Get(0).(func(*stripe.CreateStripeCustomerInput) (*domain.StripeCustomer, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*stripe.CreateStripeCustomerInput) *domain.StripeCustomer); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StripeCustomer)
		}
	}

	if rf, ok := ret.Get(1).(func(*stripe.CreateStripeCustomerInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_CreateStripeCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStripeCustomer'
type MockStripeService_CreateStripeCustomer_Call struct {
	*mock.Call
}

// CreateStripeCustomer is a helper method to define mock.On call
//   - input *stripe.CreateStripeCustomerInput
func (_e *MockStripeService_Expecter) CreateStripeCustomer(input interface{}) *MockStripeService_CreateStripeCustomer_Call {
	return &MockStripeService_CreateStripeCustomer_Call{Call: _e.mock.On("CreateStripeCustomer", input)}
}

func (_c *MockStripeService_CreateStripeCustomer_Call) Run(run func(input *stripe.CreateStripeCustomerInput)) *MockStripeService_CreateStripeCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*stripe.CreateStripeCustomerInput))
	})
	return _c
}

func (_c *MockStripeService_CreateStripeCustomer_Call) Return(_a0 *domain.StripeCustomer, _a1 error) *MockStripeService_CreateStripeCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_CreateStripeCustomer_Call) RunAndReturn(run func(*stripe.CreateStripeCustomerInput) (*domain.StripeCustomer, error)) *MockStripeService_CreateStripeCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStripePaymentMethod provides a mock function with given fields: ctx, paymentMethodID
func (_m *MockStripeService) DeleteStripePaymentMethod(ctx context.Context, paymentMethodID string) error {
	ret := _m.Called(ctx, paymentMethodID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStripePaymentMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, paymentMethodID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStripeService_DeleteStripePaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStripePaymentMethod'
type MockStripeService_DeleteStripePaymentMethod_Call struct {
	*mock.Call
}

// DeleteStripePaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethodID string
func (_e *MockStripeService_Expecter) DeleteStripePaymentMethod(ctx interface{}, paymentMethodID interface{}) *MockStripeService_DeleteStripePaymentMethod_Call {
	return &MockStripeService_DeleteStripePaymentMethod_Call{Call: _e.mock.On("DeleteStripePaymentMethod", ctx, paymentMethodID)}
}

func (_c *MockStripeService_DeleteStripePaymentMethod_Call) Run(run func(ctx context.Context, paymentMethodID string)) *MockStripeService_DeleteStripePaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStripeService_DeleteStripePaymentMethod_Call) Return(_a0 error) *MockStripeService_DeleteStripePaymentMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStripeService_DeleteStripePaymentMethod_Call) RunAndReturn(run func(context.Context, string) error) *MockStripeService_DeleteStripePaymentMethod_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerPaymentMethods provides a mock function with given fields: ctx, customerID, paymentType
func (_m *MockStripeService) GetCustomerPaymentMethods(ctx context.Context, customerID string, paymentType string) ([]*v75.PaymentMethod, error) {
	ret := _m.Called(ctx, customerID, paymentType)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPaymentMethods")
	}

	var r0 []*v75.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*v75.PaymentMethod, error)); ok {
		return rf(ctx, customerID, paymentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*v75.PaymentMethod); ok {
		r0 = rf(ctx, customerID, paymentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v75.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, customerID, paymentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_GetCustomerPaymentMethods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPaymentMethods'
type MockStripeService_GetCustomerPaymentMethods_Call struct {
	*mock.Call
}

// GetCustomerPaymentMethods is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - paymentType string
func (_e *MockStripeService_Expecter) GetCustomerPaymentMethods(ctx interface{}, customerID interface{}, paymentType interface{}) *MockStripeService_GetCustomerPaymentMethods_Call {
	return &MockStripeService_GetCustomerPaymentMethods_Call{Call: _e.mock.On("GetCustomerPaymentMethods", ctx, customerID, paymentType)}
}

func (_c *MockStripeService_GetCustomerPaymentMethods_Call) Run(run func(ctx context.Context, customerID string, paymentType string)) *MockStripeService_GetCustomerPaymentMethods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStripeService_GetCustomerPaymentMethods_Call) Return(_a0 []*v75.PaymentMethod, _a1 error) *MockStripeService_GetCustomerPaymentMethods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_GetCustomerPaymentMethods_Call) RunAndReturn(run func(context.Context, string, string) ([]*v75.PaymentMethod, error)) *MockStripeService_GetCustomerPaymentMethods_Call {
	_c.Call.Return(run)
	return _c
}

// RetrievePaymentMethod provides a mock function with given fields: ctx, paymentMethodID
func (_m *MockStripeService) RetrievePaymentMethod(ctx context.Context, paymentMethodID string) (*domain.PaymentMethod, error) {
	ret := _m.Called(ctx, paymentMethodID)

	if len(ret) == 0 {
		panic("no return value specified for RetrievePaymentMethod")
	}

	var r0 *domain.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PaymentMethod, error)); ok {
		return rf(ctx, paymentMethodID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PaymentMethod); ok {
		r0 = rf(ctx, paymentMethodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentMethodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_RetrievePaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrievePaymentMethod'
type MockStripeService_RetrievePaymentMethod_Call struct {
	*mock.Call
}

// RetrievePaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethodID string
func (_e *MockStripeService_Expecter) RetrievePaymentMethod(ctx interface{}, paymentMethodID interface{}) *MockStripeService_RetrievePaymentMethod_Call {
	return &MockStripeService_RetrievePaymentMethod_Call{Call: _e.mock.On("RetrievePaymentMethod", ctx, paymentMethodID)}
}

func (_c *MockStripeService_RetrievePaymentMethod_Call) Run(run func(ctx context.Context, paymentMethodID string)) *MockStripeService_RetrievePaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStripeService_RetrievePaymentMethod_Call) Return(_a0 *domain.PaymentMethod, _a1 error) *MockStripeService_RetrievePaymentMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_RetrievePaymentMethod_Call) RunAndReturn(run func(context.Context, string) (*domain.PaymentMethod, error)) *MockStripeService_RetrievePaymentMethod_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveStripeToken provides a mock function with given fields: ctx, tokenID
func (_m *MockStripeService) RetrieveStripeToken(ctx context.Context, tokenID string) (*v75.Token, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveStripeToken")
	}

	var r0 *v75.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v75.Token, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v75.Token); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v75.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStripeService_RetrieveStripeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveStripeToken'
type MockStripeService_RetrieveStripeToken_Call struct {
	*mock.Call
}

// RetrieveStripeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockStripeService_Expecter) RetrieveStripeToken(ctx interface{}, tokenID interface{}) *MockStripeService_RetrieveStripeToken_Call {
	return &MockStripeService_RetrieveStripeToken_Call{Call: _e.mock.On("RetrieveStripeToken", ctx, tokenID)}
}

func (_c *MockStripeService_RetrieveStripeToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockStripeService_RetrieveStripeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStripeService_RetrieveStripeToken_Call) Return(_a0 *v75.Token, _a1 error) *MockStripeService_RetrieveStripeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStripeService_RetrieveStripeToken_Call) RunAndReturn(run func(context.Context, string) (*v75.Token, error)) *MockStripeService_RetrieveStripeToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDefaultStripePaymentMethod provides a mock function with given fields: ctx, input
func (_m *MockStripeService) UpdateDefaultStripePaymentMethod(ctx context.Context, input *stripe.UpdateDefaultStripePaymentMethodInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDefaultStripePaymentMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *stripe.UpdateDefaultStripePaymentMethodInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStripeService_UpdateDefaultStripePaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDefaultStripePaymentMethod'
type MockStripeService_UpdateDefaultStripePaymentMethod_Call struct {
	*mock.Call
}

// UpdateDefaultStripePaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - input *stripe.UpdateDefaultStripePaymentMethodInput
func (_e *MockStripeService_Expecter) UpdateDefaultStripePaymentMethod(ctx interface{}, input interface{}) *MockStripeService_UpdateDefaultStripePaymentMethod_Call {
	return &MockStripeService_UpdateDefaultStripePaymentMethod_Call{Call: _e.mock.On("UpdateDefaultStripePaymentMethod", ctx, input)}
}

func (_c *MockStripeService_UpdateDefaultStripePaymentMethod_Call) Run(run func(ctx context.Context, input *stripe.UpdateDefaultStripePaymentMethodInput)) *MockStripeService_UpdateDefaultStripePaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*stripe.UpdateDefaultStripePaymentMethodInput))
	})
	return _c
}

func (_c *MockStripeService_UpdateDefaultStripePaymentMethod_Call) Return(_a0 error) *MockStripeService_UpdateDefaultStripePaymentMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStripeService_UpdateDefaultStripePaymentMethod_Call) RunAndReturn(run func(context.Context, *stripe.UpdateDefaultStripePaymentMethodInput) error) *MockStripeService_UpdateDefaultStripePaymentMethod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStripeService creates a new instance of MockStripeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStripeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStripeService {
	mock := &MockStripeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
