// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package orm

import (
	"database/sql"

	"github.com/google/uuid"
)

type Payment struct {
	ID               uuid.UUID      `db:"id" json:"ID"`
	UserID           string         `db:"user_id" json:"UserID"`
	Amount           int64          `db:"amount" json:"Amount"`
	Currency         string         `db:"currency" json:"Currency"`
	PlaidAccountID   sql.NullString `db:"plaid_account_id" json:"PlaidAccountID"`
	PlaidItemID      sql.NullString `db:"plaid_item_id" json:"PlaidItemID"`
	StripeCustomerID sql.NullString `db:"stripe_customer_id" json:"StripeCustomerID"`
	StripePaymentID  sql.NullString `db:"stripe_payment_id" json:"StripePaymentID"`
	Status           string         `db:"status" json:"Status"`
	CreatedAt        sql.NullTime   `db:"created_at" json:"CreatedAt"`
	UpdatedAt        sql.NullTime   `db:"updated_at" json:"UpdatedAt"`
}

type PlaidToken struct {
	UserID      string       `db:"user_id" json:"UserID"`
	AccessToken string       `db:"access_token" json:"AccessToken"`
	AccountID   string       `db:"account_id" json:"AccountID"`
	ItemID      string       `db:"item_id" json:"ItemID"`
	CreatedAt   sql.NullTime `db:"created_at" json:"CreatedAt"`
}

type StripeCustomer struct {
	UserID            string         `db:"user_id" json:"UserID"`
	StripeCustomerID  string         `db:"stripe_customer_id" json:"StripeCustomerID"`
	Email             sql.NullString `db:"email" json:"Email"`
	DefaultPaymentID  sql.NullString `db:"default_payment_id" json:"DefaultPaymentID"`
	PaymentMethodType sql.NullString `db:"payment_method_type" json:"PaymentMethodType"`
	BankLast4         sql.NullString `db:"bank_last4" json:"BankLast4"`
	BankName          sql.NullString `db:"bank_name" json:"BankName"`
	IsVerified        sql.NullBool   `db:"is_verified" json:"IsVerified"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"CreatedAt"`
	UpdatedAt         sql.NullTime   `db:"updated_at" json:"UpdatedAt"`
}
