// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package orm

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeletePlaidToken(ctx context.Context, userID string) error
	DeleteStripeCustomer(ctx context.Context, userID string) error
	GetAllPayments(ctx context.Context) ([]*Payment, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (*Payment, error)
	GetPlaidTokenByUserID(ctx context.Context, userID string) (*GetPlaidTokenByUserIDRow, error)
	GetStripeCustomerByUserID(ctx context.Context, userID string) (*StripeCustomer, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) error
	InsertStripeCustomer(ctx context.Context, arg InsertStripeCustomerParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateStripeCustomerDefaultPayment(ctx context.Context, arg UpdateStripeCustomerDefaultPaymentParams) error
	UpsertPlaidToken(ctx context.Context, arg UpsertPlaidTokenParams) error
}

var _ Querier = (*Queries)(nil)
