package handlers

// import (
// 	"bytes"
// 	"context"
// 	"database/sql"
// 	"encoding/json"
// 	"errors"
// 	"net/http"
// 	"net/http/httptest"
// 	"testing"

// 	"github.com/golang/mock/gomock"

// 	"github.com/GalaDe/payments-service/internal/domain"
// 	"github.com/GalaDe/payments-service/internal/services/plaid"
// 	"github.com/GalaDe/payments-service/internal/handlers/mocks"

// 	"go.temporal.io/sdk/client"
// 	"go.uber.org/zap"
// )

// /*
// These tests rely on GoMock-generated types:

// - MockRepository (from domain.Repository)
// - MockPlaidService (from plaid.PlaidService)

// Files are generated by the mockgen commands shown above.
// */

// // helper to build server with mocks
// func newServerWithMocks(repo *MockRepository, ps *MockPlaidService) *HttpServer {
// 	return &HttpServer{
// 		logger:        zap.NewNop(),
// 		worker:        client.Client(nil),
// 		repository:    repo, // used by ExchangePublicToken/GetPlaidAccounts/DeletePlaidAccount/CreateProcessorTokenForStripe
// 		plaidService:  ps,   // used by CreateLinkToken/ExchangePublicToken/GetPlaidAccounts/CreateProcessorTokenForStripe
// 		stripeService: nil,
// 	}
// }

// /* -------------------- CreateLinkToken -------------------- */

// func TestCreateLinkToken_InvalidRequest(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	srv := newServerWithMocks(mocks.NewMockRepository(ctrl), NewMockPlaidService(ctrl))

// 	req := httptest.NewRequest(http.MethodPost, "/plaid/link-token", bytes.NewBufferString(`{`)) // bad JSON
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.CreateLinkToken(rr, req)

// 	if rr.Code != http.StatusBadRequest {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusBadRequest)
// 	}
// }

// func TestCreateLinkToken_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := mocks.NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	body := map[string]any{"user_id": "user_123"}
// 	buf, _ := json.Marshal(body)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/link-token", bytes.NewBuffer(buf))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	ps.EXPECT().CreateLinkToken(gomock.Any(), "user_123").Return("ltok_abc", nil)

// 	srv.CreateLinkToken(rr, req)

// 	if rr.Code != http.StatusOK {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusOK)
// 	}
// 	var got map[string]string
// 	_ = json.Unmarshal(rr.Body.Bytes(), &got)
// 	if got["link_token"] != "ltok_abc" {
// 		t.Fatalf("link_token = %q, want %q", got["link_token"], "ltok_abc")
// 	}
// }

// /* -------------------- ExchangePublicToken -------------------- */

// func TestExchangePublicToken_InvalidRequest(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	srv := newServerWithMocks(NewMockRepository(ctrl), NewMockPlaidService(ctrl))

// 	// missing public_token
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/exchange-token", bytes.NewBufferString(`{"user_id":"u1"}`))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.ExchangePublicToken(rr, req)

// 	if rr.Code != http.StatusBadRequest {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusBadRequest)
// 	}
// }

// func TestExchangePublicToken_ExchangeError(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	reqBody := map[string]any{"user_id": "u1", "public_token": "pub_tok"}
// 	b, _ := json.Marshal(reqBody)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/exchange-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	// Adjust the return type if your PlaidService differs (e.g., plaid.ExchangeTokenResponse)
// 	ps.EXPECT().
// 		ExchangePublicToken(gomock.Any(), "pub_tok").
// 		Return(plaid.ExchangeTokenResponse{}, errors.New("plaid down"))

// 	srv.ExchangePublicToken(rr, req)

// 	if rr.Code != http.StatusInternalServerError {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusInternalServerError)
// 	}
// }

// func TestExchangePublicToken_StoreError(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	reqBody := map[string]any{"user_id": "u1", "public_token": "pub_tok"}
// 	b, _ := json.Marshal(reqBody)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/exchange-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	resp := plaid.ExchangeTokenResponse{
// 		AccessToken: "acc_t",
// 		ItemID:      "item_1",
// 		AccountID:   "acc_1",
// 	}

// 	ps.EXPECT().
// 		ExchangePublicToken(gomock.Any(), "pub_tok").
// 		Return(resp, nil)

// 	repo.EXPECT().
// 		StorePlaidToken(gomock.Any(), domain.PlaidToken{
// 			UserID:      "u1",
// 			AccessToken: "acc_t",
// 			AccountID:   "acc_1",
// 			ItemID:      "item_1",
// 		}).
// 		Return(errors.New("db error"))

// 	srv.ExchangePublicToken(rr, req)

// 	if rr.Code != http.StatusInternalServerError {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusInternalServerError)
// 	}
// }

// func TestExchangePublicToken_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	reqBody := map[string]any{"user_id": "u1", "public_token": "pub_tok"}
// 	b, _ := json.Marshal(reqBody)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/exchange-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	resp := plaid.ExchangeTokenResponse{
// 		AccessToken: "acc_t",
// 		ItemID:      "item_1",
// 		AccountID:   "acc_1",
// 	}

// 	ps.EXPECT().
// 		ExchangePublicToken(gomock.Any(), "pub_tok").
// 		Return(resp, nil)

// 	repo.EXPECT().
// 		StorePlaidToken(gomock.Any(), domain.PlaidToken{
// 			UserID:      "u1",
// 			AccessToken: "acc_t",
// 			AccountID:   "acc_1",
// 			ItemID:      "item_1",
// 		}).
// 		Return(nil)

// 	srv.ExchangePublicToken(rr, req)

// 	if rr.Code != http.StatusOK {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusOK)
// 	}
// 	var out map[string]string
// 	_ = json.Unmarshal(rr.Body.Bytes(), &out)
// 	if out["status"] != "ok" {
// 		t.Fatalf("status = %q, want %q", out["status"], "ok")
// 	}
// }

// /* -------------------- GetPlaidAccounts -------------------- */

// func TestGetPlaidAccounts_RepoNotFound(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := mocks.NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	// NOTE: handler doesn't parse user_id from query; it uses zero-value req.UserID ("")
// 	// So we expect GetPlaidToken(ctx, "").
// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "").Return(domain.PlaidToken{}, sql.ErrNoRows)

// 	req := httptest.NewRequest(http.MethodGet, "/plaid/accounts?user_id=ignored", nil)
// 	rr := httptest.NewRecorder()

// 	srv.GetPlaidAccounts(rr, req)

// 	if rr.Code != http.StatusNotFound {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusNotFound)
// 	}
// }

// func TestGetPlaidAccounts_WithBalance_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	// Still uses empty userID due to handler implementation.
// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "").Return(domain.PlaidToken{
// 		UserID:      "",
// 		AccessToken: "acc_t",
// 		AccountID:   "acc_1",
// 		ItemID:      "item_1",
// 	}, nil)

// 	ps.EXPECT().GetAccountWithBalance(gomock.Any(), "acc_t", "acc_1").Return(&plaid.AccountWithBalance{
// 		Account: plaid.Account{ID: "acc_1", Name: "Checking"},
// 		Balance: plaid.Balance{Current: 100.0, Available: 80.0},
// 	}, nil)

// 	req := httptest.NewRequest(http.MethodGet, "/plaid/accounts?with_balance=true", nil)
// 	rr := httptest.NewRecorder()

// 	srv.GetPlaidAccounts(rr, req)

// 	if rr.Code != http.StatusOK {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusOK)
// 	}
// 	var arr []map[string]any
// 	if err := json.Unmarshal(rr.Body.Bytes(), &arr); err != nil {
// 		t.Fatalf("invalid JSON: %v", err)
// 	}
// 	if len(arr) != 1 {
// 		t.Fatalf("len(arr) = %d, want 1", len(arr))
// 	}
// }

// func TestGetPlaidAccounts_Account_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "").Return(domain.PlaidToken{
// 		AccessToken: "acc_t",
// 		AccountID:   "acc_1",
// 	}, nil)

// 	ps.EXPECT().GetAccount(gomock.Any(), "acc_t", "acc_1").Return(&plaid.Account{
// 		ID:   "acc_1",
// 		Name: "Checking",
// 	}, nil)

// 	req := httptest.NewRequest(http.MethodGet, "/plaid/accounts", nil)
// 	rr := httptest.NewRecorder()

// 	srv.GetPlaidAccounts(rr, req)

// 	if rr.Code != http.StatusOK {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusOK)
// 	}
// }

// /* -------------------- CreateProcessorTokenForStripe -------------------- */

// func TestCreateProcessorTokenForStripe_InvalidRequest(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	srv := newServerWithMocks(NewMockRepository(ctrl), NewMockPlaidService(ctrl))

// 	req := httptest.NewRequest(http.MethodPost, "/plaid/processor-token", bytes.NewBufferString(`{`)) // bad JSON
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.CreateProcessorTokenForStripe(rr, req)

// 	if rr.Code != http.StatusBadRequest {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusBadRequest)
// 	}
// }

// func TestCreateProcessorTokenForStripe_RepoNotFound(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "user_123").Return(domain.PlaidToken{}, sql.ErrNoRows)

// 	body := map[string]any{"user_id": "user_123"}
// 	b, _ := json.Marshal(body)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/processor-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.CreateProcessorTokenForStripe(rr, req)

// 	if rr.Code != http.StatusNotFound {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusNotFound)
// 	}
// }

// func TestCreateProcessorTokenForStripe_PlaidError(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "user_123").Return(domain.PlaidToken{
// 		AccessToken: "acc_t",
// 		AccountID:   "acc_1",
// 	}, nil)

// 	ps.EXPECT().CreateStripeToken(gomock.Any(), "acc_t", "acc_1").Return(nil, errors.New("plaid err"))

// 	body := map[string]any{"user_id": "user_123"}
// 	b, _ := json.Marshal(body)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/processor-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.CreateProcessorTokenForStripe(rr, req)

// 	if rr.Code != http.StatusInternalServerError {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusInternalServerError)
// 	}
// }

// func TestCreateProcessorTokenForStripe_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	repo.EXPECT().GetPlaidToken(gomock.Any(), "user_123").Return(domain.PlaidToken{
// 		AccessToken: "acc_t",
// 		AccountID:   "acc_1",
// 	}, nil)

// 	btok := "btok_123"
// 	ps.EXPECT().CreateStripeToken(gomock.Any(), "acc_t", "acc_1").Return(&btok, nil)

// 	body := map[string]any{"user_id": "user_123"}
// 	b, _ := json.Marshal(body)
// 	req := httptest.NewRequest(http.MethodPost, "/plaid/processor-token", bytes.NewBuffer(b))
// 	req.Header.Set("Content-Type", "application/json")
// 	rr := httptest.NewRecorder()

// 	srv.CreateProcessorTokenForStripe(rr, req)

// 	if rr.Code != http.StatusOK {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusOK)
// 	}
// 	var out map[string]string
// 	_ = json.Unmarshal(rr.Body.Bytes(), &out)
// 	if out["stripe_bank_account_token"] != "btok_123" {
// 		t.Fatalf("token = %q, want %q", out["stripe_bank_account_token"], "btok_123")
// 	}
// }

// /* -------------------- DeletePlaidAccount -------------------- */

// func TestDeletePlaidAccount_Success(t *testing.T) {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()

// 	repo := NewMockRepository(ctrl)
// 	ps := NewMockPlaidService(ctrl)
// 	srv := newServerWithMocks(repo, ps)

// 	// NOTE: current handler does NOT read the path var; it passes empty userID to repo
// 	repo.EXPECT().DeletePlaidToken(gomock.Any(), "").Return(nil)

// 	req := httptest.NewRequest(http.MethodDelete, "/plaid/account/someUser", nil)
// 	rr := httptest.NewRecorder()

// 	srv.DeletePlaidAccount(rr, req)

// 	if rr.Code != http.StatusNoContent {
// 		t.Fatalf("status = %d, want %d", rr.Code, http.StatusNoContent)
// 	}
// }

// /* -------------------- Misc helpers -------------------- */

// func TestHandlers_ContextDoesNotPanic(t *testing.T) {
// 	// Guard test showing that passing a non-canceled ctx works
// 	ctx := context.Background()
// 	_ = ctx
// }
